# Generated by Django 2.2.7 on 2019-11-05 15:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dailyRate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Estate')),
            ],
            options={
                'ordering': ('date', 'code'),
            },
        ),
        migrations.CreateModel(
            name='RentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Estate')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Reservation')),
            ],
            options={
                'ordering': ('date', 'estate'),
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Owner'),
        ),
    ]
