# Generated by Django 2.2.6 on 2019-11-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='rentdate',
            options={'ordering': ('date', 'estate'), 'verbose_name_plural': 'Fecha de Alquiler'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date', 'code'), 'verbose_name_plural': 'Reservaciones'},
        ),
    ]
